-- Migration: init
--
-- NOTE ON PROVENANCE: this migration was authored by hand and applied/verified
-- directly against Postgres via `psql`, rather than generated by
-- `prisma migrate dev`. That command's CLI could not run in this sandbox
-- because it eagerly downloads its schema/query engine binaries from
-- binaries.prisma.sh, which this sandbox's network egress does not permit
-- (see docs/CHECKPOINT.md, "Known issues"). It mirrors prisma/schema.prisma
-- exactly and follows Prisma's standard migration folder layout
-- (this file + migration_lock.toml + tracked in the `_prisma_migrations`
-- table), so a real environment with normal internet access can run
-- `prisma migrate deploy` against it with no special handling, and
-- `prisma migrate dev` for any migration authored after this one.
--
-- This migration WAS applied to a real local Postgres instance in this
-- sandbox (via psql, not Prisma) and the constraints below were exercised
-- by tests/db-constraints.test.ts using the `pg` driver directly - see the
-- Checkpoint 2 report for what was actually verified vs. what still needs
-- verification once Prisma's CLI can run against real network access.

CREATE TYPE "EligibilityMode" AS ENUM ('ANY', 'ALL');
CREATE TYPE "ClaimStatus" AS ENUM ('CONFIRMED');
CREATE TYPE "NoncePurpose" AS ENUM ('AUTH', 'CLAIM');

CREATE TABLE "campaigns" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "eligibilityMode" "EligibilityMode" NOT NULL,
    "maxSpots" INTEGER NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "campaigns_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "campaigns_maxSpots_positive" CHECK ("maxSpots" > 0)
);

CREATE UNIQUE INDEX "campaigns_slug_key" ON "campaigns"("slug");

CREATE TABLE "campaign_collections" (
    "id" TEXT NOT NULL,
    "campaignId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "chain" TEXT NOT NULL,
    "contractAddress" TEXT NOT NULL,
    "minimumHeld" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "campaign_collections_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "campaign_collections_minimumHeld_positive" CHECK ("minimumHeld" > 0)
);

CREATE UNIQUE INDEX "campaign_collections_campaignId_chain_contractAddress_key"
    ON "campaign_collections"("campaignId", "chain", "contractAddress");
CREATE INDEX "campaign_collections_campaignId_idx" ON "campaign_collections"("campaignId");

CREATE TABLE "claims" (
    "id" TEXT NOT NULL,
    "campaignId" TEXT NOT NULL,
    "holderWallet" TEXT NOT NULL,
    "destinationWallet" TEXT NOT NULL,
    "qualifyingCollections" JSONB NOT NULL,
    "chain" TEXT NOT NULL,
    "status" "ClaimStatus" NOT NULL DEFAULT 'CONFIRMED',
    "claimSignature" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "claims_pkey" PRIMARY KEY ("id")
);

-- Core anti-duplicate-claim / anti-oversell guarantee: enforced by Postgres,
-- not just application logic. See docs/ARCHITECTURE.md / DECISIONS.md D3.
CREATE UNIQUE INDEX "claims_campaignId_destinationWallet_key"
    ON "claims"("campaignId", "destinationWallet");
CREATE INDEX "claims_campaignId_idx" ON "claims"("campaignId");
CREATE INDEX "claims_holderWallet_idx" ON "claims"("holderWallet");

CREATE TABLE "auth_nonces" (
    "id" TEXT NOT NULL,
    "wallet" TEXT NOT NULL,
    "nonce" TEXT NOT NULL,
    "purpose" "NoncePurpose" NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "consumedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "auth_nonces_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "auth_nonces_wallet_nonce_key" ON "auth_nonces"("wallet", "nonce");
CREATE INDEX "auth_nonces_wallet_purpose_idx" ON "auth_nonces"("wallet", "purpose");

CREATE TABLE "admin_users" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "admin_users_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "admin_users_email_key" ON "admin_users"("email");

ALTER TABLE "campaign_collections"
    ADD CONSTRAINT "campaign_collections_campaignId_fkey"
    FOREIGN KEY ("campaignId") REFERENCES "campaigns"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "claims"
    ADD CONSTRAINT "claims_campaignId_fkey"
    FOREIGN KEY ("campaignId") REFERENCES "campaigns"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;
